// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsmr-mATzEWGpN7ozICc-HIWYO0B3tQ9s',
    appId: '1:637820488826:web:882e00acda5ba3fb16ffc3',
    messagingSenderId: '637820488826',
    projectId: 'scholar-shopping-app',
    authDomain: 'scholar-shopping-app.firebaseapp.com',
    storageBucket: 'scholar-shopping-app.firebasestorage.app',
    measurementId: 'G-CFL0YXC67F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmCFhRqt-VRXOXAqUwT5OuhpITCcL-exI',
    appId: '1:637820488826:android:3bcaebe890cfc56f16ffc3',
    messagingSenderId: '637820488826',
    projectId: 'scholar-shopping-app',
    storageBucket: 'scholar-shopping-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGnhAwHBVZ58a6izb8d9_mXR4ZNHfHunc',
    appId: '1:637820488826:ios:e69bed3b7d083fff16ffc3',
    messagingSenderId: '637820488826',
    projectId: 'scholar-shopping-app',
    storageBucket: 'scholar-shopping-app.firebasestorage.app',
    iosBundleId: 'com.example.scholarShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGnhAwHBVZ58a6izb8d9_mXR4ZNHfHunc',
    appId: '1:637820488826:ios:e69bed3b7d083fff16ffc3',
    messagingSenderId: '637820488826',
    projectId: 'scholar-shopping-app',
    storageBucket: 'scholar-shopping-app.firebasestorage.app',
    iosBundleId: 'com.example.scholarShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsmr-mATzEWGpN7ozICc-HIWYO0B3tQ9s',
    appId: '1:637820488826:web:2f96f9b567db9c8a16ffc3',
    messagingSenderId: '637820488826',
    projectId: 'scholar-shopping-app',
    authDomain: 'scholar-shopping-app.firebaseapp.com',
    storageBucket: 'scholar-shopping-app.firebasestorage.app',
    measurementId: 'G-SCPRZYN3GG',
  );
}
